version: "3"

volumes:
    mysql_data:
        driver: local
    romm_resources:
        driver: local
    romm_redis_data:
        driver: local
    romm_library:
        driver: local
    romm_assets:
        driver: local
    romm_config:
        driver: local

services:
    romm:
        image: rommapp/romm:latest
        container_name: romm
        restart: unless-stopped
        environment:
            - DB_HOST=romm-db
            - DB_NAME=romm
            - DB_USER=romm-user
            - DB_PASSWD=securepassword123! # Cambia por una contraseña segura
            - ROMM_AUTH_SECRET_KEY=4b7e6a9f8c3d2b1e0a9f8c3d2b1e0a9f8c3d2b1e0a9f8c3d2b1e # Generada con `openssl rand -hex 32`
            - SCREENSCRAPER_USER= # Regístrate en https://www.screenscraper.fr/ y obtén tu usuario
            - SCREENSCRAPER_PASSWORD= # Obtén tu contraseña desde https://www.screenscraper.fr/
            - RETROACHIEVEMENTS_API_KEY= # Obtén tu clave en https://retroachievements.org/controlpanel.php
            #- STEAMGRIDDB_API_KEY=your_steamgriddb_api_key # Obtén tu clave en https://www.steamgriddb.com/profile/preferences/api#
            - HASHEOUS_API_ENABLED=true
        volumes:
            - romm_resources:/romm/resources
            - romm_redis_data:/redis-data
            - romm_library:/romm/library
            - romm_assets:/romm/assets
            - romm_config:/romm/config
        ports:
            - 80:8080
        depends_on:
            romm-db:
                condition: service_healthy
                restart: true

    romm-db:
        image: mariadb:latest
        container_name: romm-db
        restart: unless-stopped
        environment:
            - MARIADB_ROOT_PASSWORD=rootsecurepassword456! # Cambia por una contraseña segura
            - MARIADB_DATABASE=romm
            - MARIADB_USER=romm-user
            - MARIADB_PASSWORD=securepassword123! # Debe coincidir con DB_PASSWD en el servicio romm
        volumes:
            - mysql_data:/var/lib/mysql
        healthcheck:
            test: [CMD, healthcheck.sh, --connect, --innodb_initialized]
            start_period: 30s
            start_interval: 10s
            interval: 10s
            timeout: 5s
            retries: 5
