version: "3"
volumes:
    webtop_config_data:
        driver: local
services:
  webtop:
    image: lscr.io/linuxserver/webtop:latest
    container_name: webtop
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - LC_ALL=es_ES.UTF-8
      - TITLE=Mi escritorio #optional
      #- CUSTOM_USER=
      #- PASSWORD=
    volumes:
      - webtop_config_data:/config
    ports:
      - 3000:3000
      - 3001:3001
    shm_size: "1gb"
    restart: unless-stopped
